{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gtw"
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  {{- if .Values.gateway.http }}
  - protocol: HTTP
    port: 80
    name: http-web-gw
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}
  {{- if .Values.gateway.https }}
  - protocol: HTTPS
    port: 443
    name: https-web-gw
    tls:
      certificateRefs:
      - name: {{ .Values.gateway.tlsSecretName }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo-http
spec:
  parentRefs:
  - name: "{{ .Chart.Name }}-gtw"
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - backendRefs:
    - name: "{{ .Values.service.name }}-v1"
      port: {{ .Values.service.port }}
      weight: {{- if .Values.canary.enabled }} {{ sub 100 .Values.canary.weight }} {{- else }} 100 {{- end }}
    {{- if .Values.canary.enabled }}
    - name: "{{ .Values.service.name }}-v2"
      port: {{ .Values.service.port }}
      weight: {{ .Values.canary.weight }}
    {{- end }}

{{- end }}
