apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc-v1"
  labels:
    app: "{{ .Release.Name }}-v1"
spec:
  selector:
    app: "{{ .Release.Name }}-v1"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}

---
{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc-v2"
  labels:
    app: "{{ .Release.Name }}-v2"
spec:
  selector:
    app: "{{ .Release.Name }}-v2"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
{{- end }}