replicaCount: 3

image:
  repository: uonyeka/canary-demo
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

gateway:
  enabled: true
  https: true
  http: true
  tlsSecretName: "canary-demo-tls"
  gatewayClassName: "nginx"
  hostname: "site.multiclouds.tech"

canary:
  enabled: false
  replicaCount: 1
  image:
    tag: "v3"

config:
  main:
    appColor: "white"
    welcomeMessage: "Welcome to Upcommerce.com!"
  canary:
    appColor: "yellow"
    welcomeMessage: "Welcome to Upcommerce.com Canary!"

serviceMonitor:
  enabled: true

slo:
  availability:
    target: 99.9
    errorBudgetPeriod: "30d"
